---
baseurl: "/dogsitter"
title: Armonk Dogsitter
url: https://maxjacobson.github.io/dogsitter/
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- Gemfile
- Gemfile.lock
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ".ruby-version"
- bin/
available: false
