baseurl: "/dogsitter" # the subpath of your site, e.g. /blog
title: "Armonk Dogsitter"
url: "https://maxjacobson.github.io/dogsitter/" # the base hostname & protocol for your site, e.g. http://example.com

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .ruby-version
  - bin/
