baseurl: "" # the subpath of your site, e.g. /blog
title: "Armonk Dogsitter"
url: "" # the base hostname & protocol for your site, e.g. http://example.com

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
