name: Toggle availability

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "toggle"
  cancel-in-progress: true

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 1 # Increment this number if you need to re-download cached gems

      - name: Toggle availability
        run: bin/toggle

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _data/properties.yml
          git commit --message "Toggled availability"
          git push

      - name: Trigger build
        run: gh workflow run Deploy
